apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-react
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: react-container
        image: react-app:latest
        resources:
          limits:
            cpu: "0.5"  # 0.5 CPU cores
            memory: "256Mi"  # 256 megabytes
          requests:
            cpu: "0.1"  # 0.1 CPU cores
            memory: "128Mi"  # 128 megabytes
