# Use the official Node.js image as the base image
FROM node:14

RUN npm install -g npm

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application code to the container
COPY . .

# Install app dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose port 80 (the default port for serving HTTP)
EXPOSE 80

# Start the React app when the container starts
CMD ["npm", "start"]
